sudo: required
cache: apt

env:
    # default naming-patter: branch-commitid.PDF
    - outputfilename="${TRAVIS_BRANCH}-${TRAVIS_COMMIT}"

before_install:
    # as somehow no biber package is available for ubuntu 12.04 via apt, let's just download it directly
    #- sudo wget "http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/0.9.9/binaries/Linux/biber-linux_x86_64.tar.gz"
    - sudo wget "https://phildiegmann.s3.amazonaws.com/downloads/biber/0.9.9/biber-linux_x86_64.tar.gz"
    - tar xzf biber-linux_x86_64.tar.gz
    # add latest latex packages to apt-get repos
    - sudo add-apt-repository ppa:texlive-backports/ppa -y

install:
    # update apt-get to get newest versions
    - sudo apt-get update
    # get basic LaTeX stuff
    - sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-pictures
    # get LaTeX 3
    - sudo apt-get install texlive-latex3
    # get basic biblatex stuff
    - sudo apt-get install texlive-bibtex-extra biblatex 
    # get chktex to check our LaTeX
    - sudo apt-get install chktex
 
script:
    # if we have a TAG provided, use this as filename: tag.PDF
    - "echo ${#TRAVIS_TAG}; if [ ${#TRAVIS_TAG} -gt 0 ]; then outputfilename=${TRAVIS_TAG}; fi"

    - chktex -W # Print version information.
    - chktex -q -n 6 *.tex chapters.*.tex 2>/dev/null | tee lint.out
    # If lint output is non-empty report an error.
    #- test ! -s lint.out

    # now actually build the PDF
    - pdflatex -jobname=${outputfilename} main.tex
    - ./biber ${outputfilename}
    - pdflatex -jobname=${outputfilename} main.tex

deploy:
    provider: releases
    api_key:
        secure: ${github_api_key}
    file:
        - ${outputfilename}.pdf
    skip_cleanup: true
    on:
        tags: true